[package]
name = "w3registrar"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
anyhow = "1.0.86"
warp = "0.3"
futures = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
toml = "0.8.19"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
subxt = "0.37.0"
serde_json = "1.0.125"
hex = "0.4.3"
uuid = { version = "1.10.0", features = ["v4", "macro-diagnostics"] }
async-trait = "0.1.81"
rand = "0.8.5"
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8.0", features = [ "runtime-tokio", "sqlite" ] }

# Disabled, because it conflicts with sqlx. Something to do with SQlite.
#matrix-sdk = "0.7.1"
