[package]
name = "w3registrar"
version = "0.4.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
anyhow = "1.0.86"
futures = "0.3.30"
tokio = { version = "1.39.2", features = ["full", "signal"] }
toml = "0.8.19"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
subxt = { version = "0.38", features = ["substrate-compat"] }
serde_json = "1.0.125"
hex = "0.4.3"
uuid = { version = "1.10.0", features = ["v4", "macro-diagnostics"] }
async-trait = "0.1.81"
rand = "0.8.5"
chrono = { version = "0.4", features = ["serde"] }
# Pulling matrix-sdk in from GitHub, as the latest stable crate causes a
# conflict with sqlx. Something to do with SQlite.
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", rev = "19e89bbd6a0df1c4a5636252b02b9e16cc7ab44d" }
tokio-stream = "0.1.16"
async-stream = "0.3.6"
sp-core = "35.0.0"
tokio-tungstenite = "0.26.0"
futures-util = "0.3.31"
subxt-signer = "0.38"
redis = { version = "0.28", features = ["aio", "json", "tokio-comp", "uuid"] }
url = "2"
once_cell = "1.20"
tungstenite = "0.26.1"
strum = { version = "0.26", features = ["derive"] }
imap = "2.4.1"
native-tls = "0.2.12"
mail-parser = "0.9.4"

[dev-dependencies]
pretty_assertions = "1.4.1"
