[registrar]

[registrar.rococo]
endpoint = "wss://dev.rotko.net/people-rococo/"
registrar_index = 0
keystore_path = "./.keyfile.rococo" # IdentityJudgement proxy's pneumonic/private keypath
registrar_account = "5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL" # ferdie as registrar
fields = ["email","matrix", "twitter", "discord", "display_name"]

[registrar.paseo]
endpoint = "wss://people-paseo.dotters.network"
registrar_index = 1
keystore_path = "./.keyfile.example"
registrar_account = "12BtBrcorHAvSeTLYo6YTq8kdiRG948vkvmxHEmSzZjwZ97u"
fields = ["email","matrix", "twitter", "discord", "display_name"]

[http]
host = "0.0.0.0"
port = 3000

[websocket]
host = "0.0.0.0"
port = 8080

[redis]
host = "0.0.0.0"
port = 6379
# leave them empty if you don't wish to an account
# username = "asdf"
# password = "abc"

[adapter]
[adapter.matrix]
homeserver = "https://matrix.beeper.com"
username = "regbot"
password = "abc123"
security_key = "EfT0 1WXL nIi8 v1Zx 15c8 B8Ux bKdS fLUZ 5uVk zje7 KYFj ZiLf"
admins = ["@sara:matrix.org", "@bill:matrix.org"]
state_dir = "/tmp/matrix_"

[adapter.email]
email = "w3reg@rotko.net"
username = "w3reg"
password = "pw"
name = "w3registrar"
mailbox = "INBOX"
server = "mail.rotko.net"
port = 143                # IMAPS port

[adapter.github]
client_id = "..."
client_secret = "..."
gh_url = "https://github.com/login/oauth/authorize"
redirect_url = "http://example.com/oauth/callback/github"
