[matrix]
homeserver = "https://matrix.org"
username = "regbot"
password = "abc123"
state_dir = "/tmp/matrix_state"
security_key = "EfT0 1WXL nIi8 v1Zx 15c8 B8Ux bKdS fLUZ 5uVk zje7 KYFj ZiLf"
admins = [
    "@sara:matrix.org",
    "@bill:matrix.org",
]

[redis]
url = "redis://127.0.0.1"
timeout = 300

[node]
endpoint = "wss://dev.rotko.net/people-rococo/"
registrar_index = 0
keystore_path = "./keyfile"
proxy_account = "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty" # hot wallet(pk in keyfile)
registrar_account = "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY" # registrar (pk cold stored)

[websocket]
ip = [127,0,0,1]
port = 8080
