services:
  redis:
    image: redis:7-alpine
    container_name: redis-${VERSION_TAG:-prod}
    restart: always
    ports:
      - "127.0.0.1:${REDIS_PORT:-16379}:6379"
    volumes:
      - redis_data:/data
    # networks:
    #   - w3r_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: ["redis-server", "--bind", "0.0.0.0"]

  w3registrar:
    image: w3registrar:${VERSION_TAG:-prod}
    container_name: ${SERVICE_NAME:-w3registrar}
    pull_policy: never
    restart: unless-stopped
    command: ["w3registrar"]
    network_mode: "host"
    # networks:
    #   - w3r_network
    volumes:
      - ${CONFIG_PATH:-./config.toml}:/etc/w3registrar/config.toml:ro
      - ${KEYFILE:-./keyfile}:/etc/w3registrar/keyfile:ro
      - ${SSL_CERT:-./ssl_cert.pem}:/etc/w3registrar/ssl_cert.pem:ro
    environment:
      - CONFIG_PATH=/etc/w3registrar/config.toml
      - RUST_LOG=info
      - KEYFILE_PATH=/etc/w3registrar/keyfile

volumes:
  # postgres_data:
  redis_data:
  # NOTE: access redis from hosts networkgs
# networks:
#   w3r_network:
#     name: w3r_${VERSION_TAG:-prod}_network
#     driver: bridge
