services:
  redis:
    image: redis:7-alpine
    container_name: redis-prod
    ports:
      - "127.0.0.1:66379:6379"
    volumes:
      - redis_data:/data
    networks:
      - w3r_prod_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: ["redis-server", "--bind", "0.0.0.0"] 

  w3registrar:
    container_name: api-w3registrar
    image: w3registrar:prod
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "68080:8080"
    networks:
      - w3r_prod_network
    volumes:
      - ./config.toml:/etc/w3registrar/config.toml:ro
      - ./.keyfile:/etc/w3registrar/keyfile:ro
    environment:
      - CONFIG_PATH=/etc/w3registrar/config.toml
      - RUST_LOG=info
      - KEYFILE_PATH=/etc/w3registrar/keyfile
    healthcheck:
      test:
        [ "CMD-SHELL", "test -f /etc/w3registrar/config.toml && test -f /etc/w3registrar/keyfile", ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  redis_data:

networks:
  w3r_prod_network:
    driver: bridge
