# deploy-prod.yaml (API)
name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Are you sure you want to deploy to production? (type "DEPLOY" to confirm)'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to API
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_deploy == 'DEPLOY'
    env:
      SERVER_USER: w3reg
      SERVER_HOST: api.w3reg.org
      SERVER_PORT: 22
      DEPLOY_PATH: /home/w3reg/api.w3reg.org
      SERVICE_NAME: w3registrar-api
      SOURCE_PATH: /home/w3reg/sapi.w3reg.org/w3registrar-sapi
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ env.SERVER_PORT }} ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy binary to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ env.SERVER_PORT }}" \
            ${{ env.SOURCE_PATH }} \
            ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.DEPLOY_PATH }}/${{ env.SERVICE_NAME }}

      - name: Restart service
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ env.SERVER_PORT }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << EOF
            sudo systemctl daemon-reload
            sudo systemctl restart ${{ env.SERVICE_NAME }}
            sudo systemctl status ${{ env.SERVICE_NAME }} --no-pager
          EOF
