# deploy-prod-docker.yaml (API)
name: Deploy API with dockers

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Are you sure you want to deploy to production? (type "DEPLOY" to confirm)'
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build and Deploy API docker
    runs-on: ubuntu-latest
    env:
      SERVER_USER: w3reg
      SERVER_HOST: 135.181.202.179
      SERVER_PORT: 22
      DEPLOY_PATH: /home/w3reg/api.w3reg.org
      SERVICE_NAME: w3registrar-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Create Required files
        env:
          CONFIG_CONTENT: ${{ secrets.CONFIG_API_DOCKER }}
          KEYFILE_ROCOCO: ${{ secrets.KEYFILE_ROCOCO }}
          KEYFILE_PASEO: ${{ secrets.KEYFILE_PASEO }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ env.SERVER_PORT }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'EOF'
            set -euo pipefail
            cd ${{ env.DEPLOY_PATH }}
            
            # Create config.toml
            cat > config.docker.toml << 'CONFIGEND'
            $CONFIG_CONTENT
            CONFIGEND
            
            # Create .keyfile.rococo
            cat > .keyfile.rococo << 'ROCOCOEND'
            $KEYFILE_ROCOCO
            ROCOCOEND
            
            # Create .keyfile.paseo
            cat > .keyfile.paseo << 'PASEOEND'
            $KEYFILE_PASEO
            PASEOEND
          EOF

      - name: Deploy on Remote Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ env.SERVER_PORT }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'EOF'
            set -euo pipefail
            cd ${{ env.DEPLOY_PATH }}
            docker compose -f ./docker-compose.yaml down || true
            docker image rm w3registrar:prod || true
            docker tag w3registrar:staging w3registrar:prod
            docker compose -f ./docker-compose.yaml up -d
          EOF
