name: Release binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Release Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      
      - name: Enable Nix Flakes
        uses: DeterminateSystems/magic-nix-cache-action@v2
        
      - name: Build Release Binary
        run: nix build .#defaultPackage.x86_64-linux
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: result/bin/w3registrar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
