name: Release binaries
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update lockfile
        run: cargo update

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.platform.target }}/release/w3registrar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
