name: Release binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
          - os_name: Linux-aarch64
            target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
          if [ "${{ matrix.platform.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          fi

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true

      # - name: Package Binary
      #   run: |
      #     cd target/${{ matrix.platform.target }}/release
      #     tar czf ../../../w3registrar-${{ matrix.platform.os_name }}.tar.gz w3registrar
      #     cd -
      #
      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: w3registrar-${{ matrix.platform.os_name }}.tar.gz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
